-- logical_table: process_event_data
-- physical_fqn: icebase.agenticai_devicesupport.process_event_data
-- Cross-table joins: see ../../join_graph.yaml at bundle root (outside model/).
SELECT
  "device_id" AS device_id,
  TRY_CAST("cpuusage" AS DOUBLE) AS cpuusage,
  CAST("processcount" AS DOUBLE) AS processcount,
  "dataset_context_id" AS dataset_context_id,
  "dataset_id" AS dataset_id,
  "device_context_id" AS device_context_id,
  "item_context_id" AS item_context_id,
  "numofprocesspercpuusage" AS numofprocesspercpuusage,
  "numofthreadpercpuusage" AS numofthreadpercpuusage,
  "systemstate" AS systemstate,
  CAST("threadcount" AS DOUBLE) AS threadcount,
  "item_id" AS item_id,
  "item_name" AS item_name,
  "item_time" AS item_time,
  "report_time" AS report_time,
  CAST("schema_ver" AS DOUBLE) AS schema_ver,
  "subscription_id" AS subscription_id,
  "subscription_ids" AS subscription_ids,
  "process_1_cpuusageperc" AS process_1_cpuusageperc,
  "process_1_filedescription" AS process_1_filedescription,
  "process_1_filemodifieddate" AS process_1_filemodifieddate,
  "process_1_filename" AS process_1_filename,
  "process_1_filepublisher" AS process_1_filepublisher,
  "process_1_fileversion" AS process_1_fileversion,
  CAST("process_1_id" AS DOUBLE) AS process_1_id,
  "process_1_productname" AS process_1_productname,
  "process_1_threadcpuusageperc" AS process_1_threadcpuusageperc,
  CAST("process_1_threadid" AS DOUBLE) AS process_1_threadid,
  "process_2_cpuusageperc" AS process_2_cpuusageperc,
  "process_2_filedescription" AS process_2_filedescription,
  "process_2_filemodifieddate" AS process_2_filemodifieddate,
  "process_2_filename" AS process_2_filename,
  "process_2_filepublisher" AS process_2_filepublisher,
  "process_2_fileversion" AS process_2_fileversion,
  CAST("process_2_id" AS DOUBLE) AS process_2_id,
  "process_2_productname" AS process_2_productname,
  "process_2_threadcpuusageperc" AS process_2_threadcpuusageperc,
  CAST("process_2_threadid" AS DOUBLE) AS process_2_threadid,
  "process_3_cpuusageperc" AS process_3_cpuusageperc,
  "process_3_filedescription" AS process_3_filedescription,
  "process_3_filemodifieddate" AS process_3_filemodifieddate,
  "process_3_filename" AS process_3_filename,
  "process_3_filepublisher" AS process_3_filepublisher,
  "process_3_fileversion" AS process_3_fileversion,
  CAST("process_3_id" AS DOUBLE) AS process_3_id,
  "process_3_productname" AS process_3_productname,
  "process_3_threadcpuusageperc" AS process_3_threadcpuusageperc,
  CAST("process_3_threadid" AS DOUBLE) AS process_3_threadid,
  "process_4_cpuusageperc" AS process_4_cpuusageperc,
  "process_4_filedescription" AS process_4_filedescription,
  "process_4_filemodifieddate" AS process_4_filemodifieddate,
  "process_4_filename" AS process_4_filename,
  "process_4_filepublisher" AS process_4_filepublisher,
  "process_4_fileversion" AS process_4_fileversion,
  CAST("process_4_id" AS DOUBLE) AS process_4_id,
  "process_4_productname" AS process_4_productname,
  "process_4_threadcpuusageperc" AS process_4_threadcpuusageperc,
  CAST("process_4_threadid" AS DOUBLE) AS process_4_threadid,
  "process_5_cpuusageperc" AS process_5_cpuusageperc,
  "process_5_filedescription" AS process_5_filedescription,
  "process_5_filemodifieddate" AS process_5_filemodifieddate,
  "process_5_filename" AS process_5_filename,
  "process_5_filepublisher" AS process_5_filepublisher,
  "process_5_fileversion" AS process_5_fileversion,
  CAST("process_5_id" AS DOUBLE) AS process_5_id,
  "process_5_productname" AS process_5_productname,
  "process_5_threadcpuusageperc" AS process_5_threadcpuusageperc,
  CAST("process_5_threadid" AS DOUBLE) AS process_5_threadid
FROM icebase.agenticai_devicesupport.process_event_data
