name: device-intelligence-360
version: v1alpha
type: lens
tags:
  - Tier.Generated
  - SemanticModelAgent
description: |
  The Device Intelligence 360 data product provides stakeholders with a comprehensive view of enterprise laptop fleets, focusing on critical metrics such as device health, memory and storage usage, and network connectivity. By analyzing these dimensions, decision-makers can identify potential device failures early, prioritize remediation efforts, and enhance overall fleet performance. This lens ensures that sensitive customer information is protected while delivering valuable insights that support proactive management and operational efficiency. Ultimately, it empowers organizations to optimize their IT resources and improve service delivery.
layer: user
owner: manpreetsingh
workspace: public
lens:
  compute: runnable-default
  runAsUser: manpreetsingh
  secrets:
    - name: githubrepo
      allKeys: true
  source:
    type: minerva
    name: minervac
    catalog: icebase
  repo:
    url: https://github.com/sunnysnowflake02-cell/device-360
    lensBaseDir: device-360/device-360-built/model
    syncFlags:
      - --ref=main
  api:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  router:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  worker:
    logLevel: info
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  metric:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
