-- logical_table: device_data
-- physical_fqn: icebase.agenticai_devicesupport.device_data
-- Cross-table joins: see ../../join_graph.yaml at bundle root (outside model/).
SELECT
  "device_id" AS device_id,
  "customer_id" AS customer_id,
  "context_id" AS context_id,
  "dataset_id" AS dataset_id,
  CAST("device_context_datetime" AS TIMESTAMP(6)) AS device_context_datetime,
  "device_context_id" AS device_context_id,
  "device_bios_version" AS device_bios_version,
  "device_brand" AS device_brand,
  "device_ec_version" AS device_ec_version,
  "device_enclosuretype" AS device_enclosuretype,
  "device_family" AS device_family,
  "device_id2" AS device_id2,
  CAST("device_info_datetime" AS TIMESTAMP(6)) AS device_info_datetime,
  "device_manufacturer" AS device_manufacturer,
  "device_modeltype" AS device_modeltype,
  "device_name" AS device_name,
  CAST("device_purchase_date" AS TIMESTAMP(6)) AS device_purchase_date,
  "device_smbios_version" AS device_smbios_version,
  "device_subbrand" AS device_subbrand,
  "os_country" AS os_country,
  "os_language" AS os_language,
  "os_name" AS os_name,
  "os_update_description" AS os_update_description,
  "os_update_title" AS os_update_title,
  "os_version" AS os_version,
  "country_code" AS country_code,
  "country_name" AS country_name,
  "language_code" AS language_code,
  "language_name" AS language_name,
  CAST("region_info_datetime" AS TIMESTAMP(6)) AS region_info_datetime,
  "region_name" AS region_name,
  CAST("report_time" AS TIMESTAMP(6)) AS report_time,
  "device_inventory_location" AS device_inventory_location,
  CAST("schema_ver" AS DOUBLE) AS schema_ver,
  "subscription_id" AS subscription_id,
  "subscription_ids" AS subscription_ids,
  "udc_channel" AS udc_channel,
  "udc_id" AS udc_id,
  CAST("udc_info_datetime" AS TIMESTAMP(6)) AS udc_info_datetime,
  "udc_key" AS udc_key,
  "udc_name" AS udc_name,
  CAST("udc_version" AS DOUBLE) AS udc_version
FROM icebase.agenticai_devicesupport.device_data
